# Generated by Django 4.1.1 on 2022-12-29 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InternetUsageData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('mac_address', models.CharField(max_length=100)),
                ('start_time', models.DateTimeField()),
                ('usage_time', models.TimeField()),
                ('upload', models.FloatField()),
                ('download', models.FloatField()),
            ],
        ),
    ]
