# Generated by Django 4.1.1 on 2022-12-29 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info_tools', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='internetusagedata',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='internetusagedata',
            table='InternetUsageData',
        ),
    ]
